### ISSUE TITLE
search button problem

### ISSUE THREAD

**Issue by hsoylu34** [moko256/twitlatte#38] opened 2018-12-02 08:01 UTC
Search button didn't work. Android 9.0 
https://del.dog/Twitlatte.pl

**Comment by moko256** [comment] 2018-12-02 08:07
Thanks! I'll fix it soon.

**Comment by moko256** [comment] 2018-12-09 01:04
Fixed by commit #aabb7d4.
In the next version, fatal crash like this will not be caused by internet or the other error.

**Closed by moko256** 2018-12-09 01:04 UTC
